"""Verify the complete Gradle release matrix before atomically archiving APKs.

The manifest is generated by gradle/release-archive.gradle from configured
variants, never inferred from old APKs. No signing secret is read or logged here.
"""
from __future__ import annotations

from collections import Counter
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import struct
import subprocess
import tempfile
import zipfile
import zlib


class ReleaseError(ValueError):
    pass


def require(condition, message):
    if not condition:
        raise ReleaseError(message)


def within(path, root):
    resolved = Path(path).resolve()
    require(resolved.is_relative_to(Path(root).resolve()), f"Path leaves allowed directory: {path}")
    return resolved


def read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8-sig"))


def command(args):
    result = subprocess.run([str(item) for item in args], capture_output=True, text=True, encoding="utf-8", errors="replace")
    require(result.returncode == 0, f"APK verification failed ({Path(str(args[0])).name}): {result.stderr.strip() or result.stdout.strip()}")
    return result.stdout


def abi_of(element):
    filters = element.get("filters", [])
    require(all(f["filterType"] == "ABI" for f in filters), "Unsupported density/language split in release matrix")
    require(len(filters) <= 1, "Multiple ABI filters on one APK")
    return filters[0]["value"] if filters else "universal"


def collect(manifest):
    """Reject missing/extra variants, old versions, duplicate ABIs and unlisted APKs."""
    root = Path(manifest["apkRoot"]).resolve()
    expected = {v["name"]: v for v in manifest["variants"]}
    require(len(expected) == len(manifest["variants"]) and expected, "Empty or duplicate configured release variants")
    metadata = {}
    for path in root.rglob("output-metadata.json"):
        data = read_json(path)
        name = data.get("variantName", "")
        if name.lower().endswith("release"):
            require(name not in metadata, f"Duplicate release metadata: {name}")
            metadata[name] = (path, data)
    require(set(metadata) == set(expected), f"Release variants differ: expected {sorted(expected)}, found {sorted(metadata)}")
    result = []
    for name, variant in expected.items():
        path, data = metadata[name]
        require(data.get("applicationId") == variant["applicationId"], f"Wrong application ID: {path}")
        outputs = variant["outputs"]
        expected_abis = [output["abi"] for output in outputs]
        actual_abis = [abi_of(item) for item in data["elements"]]
        require(len(set(actual_abis)) == len(actual_abis), f"Duplicate ABI output: {name}")
        require(sorted(actual_abis) == sorted(expected_abis), f"Incomplete ABI matrix: {name}: expected {expected_abis}, found {actual_abis}")
        listed = set()
        for element in data["elements"]:
            abi = abi_of(element)
            wanted = next(item for item in outputs if item["abi"] == abi)
            require(element.get("versionCode") == wanted["versionCode"] and element.get("versionName") == wanted["versionName"], f"Stale version in {name}/{abi}")
            apk = within(path.parent / element["outputFile"], path.parent)
            require(apk.is_file() and apk.suffix == ".apk", f"Missing APK: {apk}")
            listed.add(apk)
            result.append((apk, variant, wanted))
        actual = {within(p, root) for p in path.parent.glob("*.apk")}
        require(actual == listed, f"Unlisted APKs beside release metadata: {path.parent}")
    return result


def verify_elf64(data, label):
    require(data[:4] == b"\x7fELF", f"Invalid native library: {label}")
    if data[4] != 2:
        return
    endian = "<" if data[5] == 1 else ">"
    phoff = struct.unpack_from(endian + "Q", data, 32)[0]
    phsize, phnum = struct.unpack_from(endian + "HH", data, 54)
    for index in range(phnum):
        kind, _, offset, address, _, _, _, alignment = struct.unpack_from(endian + "IIQQQQQQ", data, phoff + index * phsize)
        if kind == 1:
            require(alignment >= 16384 and (offset - address) % 16384 == 0, f"64-bit ELF is not 16 KB aligned: {label}")


def verify_native(apk, abi, native_abis):
    with zipfile.ZipFile(apk) as archive:
        libraries = [item for item in archive.infolist() if re.fullmatch(r"lib/[^/]+/[^/]+\.so", item.filename)]
        actual_abis = {item.filename.split("/")[1] for item in libraries}
        expected_abis = set(native_abis) if abi == "universal" else {abi}
        require(actual_abis == expected_abis, f"Native ABIs differ in {apk.name}: expected {sorted(expected_abis)}, found {sorted(actual_abis)}")
        for item in libraries:
            verify_elf64(archive.read(item), f"{apk.name}:{item.filename}")
            if item.compress_type == zipfile.ZIP_STORED:
                with apk.open("rb") as stream:
                    stream.seek(item.header_offset + 26)
                    name_len, extra_len = struct.unpack("<HH", stream.read(4))
                require((item.header_offset + 30 + name_len + extra_len) % 16384 == 0, f"Uncompressed native library is not ZIP aligned: {apk.name}:{item.filename}")
    return sorted(actual_abis)


def verify_apk(apk, variant, output, manifest):
    sdk_tools = Path(manifest["buildToolsDirectory"])
    executable = "aapt2.exe" if os.name == "nt" else "aapt2"
    badging = command([sdk_tools / executable, "dump", "badging", apk])
    match = re.search(r"package: name='([^']+)' versionCode='(\d+)' versionName='([^']*)'", badging)
    require(match is not None, f"Cannot read APK identity: {apk.name}")
    require(match.groups() == (variant["applicationId"], str(output["versionCode"]), output["versionName"]), f"APK identity/version differs from current Gradle configuration: {apk.name}")
    signature = command([manifest["javaExecutable"], "-jar", sdk_tools / "lib" / "apksigner.jar", "verify", "--verbose", "--print-certs", apk])
    signers = re.findall(r"Signer #\d+ certificate SHA-256 digest: ([0-9a-fA-F]+)", signature)
    require(signers == [manifest["signerSha256"]], f"APK was not signed with the configured release key: {apk.name}")
    require("CN=Android Debug" not in signature, f"Debug certificate cannot be published: {apk.name}")
    return verify_native(apk, output["abi"], variant["nativeAbis"])


def archive_release(manifest, verify_only=False):
    entries = collect(manifest)
    verified = []
    version_abi_counts = Counter((output["versionName"], output["abi"]) for _, _, output in entries)
    for apk, variant, output in entries:
        native_abis = verify_apk(apk, variant, output, manifest)
        content = apk.read_bytes()
        crc = f"{zlib.crc32(content) & 0xffffffff:08X}"
        flavor = variant["name"][:-7].strip("-") if variant["name"] != "release" else ""
        suffix = f"-{flavor.lower()}" if flavor and version_abi_counts[(output["versionName"], output["abi"])] > 1 else ""
        filename = f"{manifest['projectName']}-v{output['versionName']}{suffix}-{output['abi']}-{crc}.apk"
        require(re.fullmatch(r"[A-Za-z0-9._+-]+\.apk", filename), "Unsafe release filename")
        verified.append((apk, {"file": filename, "variant": variant["name"], "applicationId": variant["applicationId"], "versionName": output["versionName"], "versionCode": output["versionCode"], "abi": output["abi"], "nativeAbis": native_abis, "crc32": crc, "sha256": hashlib.sha256(content).hexdigest()}))
    require(len({item["file"] for _, item in verified}) == len(verified), "Archive filename collision")
    if verify_only:
        print(f"Verified {len(verified)} signed release APKs; no files written")
        return
    root = Path(manifest["projectRoot"]).resolve()
    destination = within(manifest["destination"], root / "releases")
    require(destination != root / "releases", "Use a versioned releases subdirectory")
    revision = subprocess.run(["git", "-C", str(root), "rev-parse", "HEAD"], capture_output=True, text=True)
    status = subprocess.run(["git", "-C", str(root), "status", "--porcelain", "--untracked-files=normal"], capture_output=True, text=True)
    receipt = {"archiveSchema": 1, "projectName": manifest["projectName"], "sourceRevision": revision.stdout.strip() if revision.returncode == 0 else None, "sourceDirty": bool(status.stdout.strip()) if status.returncode == 0 else None, "signerSha256": manifest["signerSha256"], "artifacts": [item for _, item in verified]}
    if destination.exists():
        previous_path = destination / "release-manifest.json"
        require(previous_path.is_file(), f"Refusing to replace unmanaged directory: {destination}")
        previous = read_json(previous_path)
        require(previous.get("archiveSchema") == 1 and previous.get("projectName") == manifest["projectName"], "Existing archive is owned by another producer")
        owned = {"release-manifest.json"} | {item["file"] for item in previous["artifacts"]}
        require({item.name for item in destination.iterdir()} == owned, "Existing archive contains untracked files")
        require(all(item.is_file() and not item.is_symlink() for item in destination.iterdir()), "Existing archive contains unsafe entries")
    destination.parent.mkdir(parents=True, exist_ok=True)
    stage = Path(tempfile.mkdtemp(prefix=".release-stage-", dir=destination.parent))
    backup = stage.with_name(stage.name + "-previous")
    try:
        for source, item in verified:
            target = stage / item["file"]
            shutil.copyfile(source, target)
            require(hashlib.sha256(target.read_bytes()).hexdigest() == item["sha256"], "APK changed during archive copy")
        (stage / "release-manifest.json").write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
        if destination.exists():
            destination.rename(backup)
        try:
            stage.rename(destination)
        except BaseException:
            if backup.exists():
                backup.rename(destination)
            raise
        if backup.exists():
            shutil.rmtree(within(backup, destination.parent))
    finally:
        if stage.exists():
            shutil.rmtree(within(stage, destination.parent))
    print(f"Archived {len(verified)} verified signed APKs: {destination}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--verify-only", action="store_true")
    args = parser.parse_args()
    try:
        archive_release(read_json(args.manifest), args.verify_only)
    except (ReleaseError, OSError, KeyError, json.JSONDecodeError, struct.error, zipfile.BadZipFile) as error:
        parser.exit(1, f"Release verification failed: {error}\n")


if __name__ == "__main__":
    main()
